### ISSUE TITLE
Meta: Release 0.1

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-live#1]
## Goals

- good enough for live SSB on the GPU
- good enough code quality, good enough performance
- experimental API

## What's still missing:

- [x] convenience functions for plotting 
- [x] convenience functions for running UDFs on live data streams
- [x] test infra and some test coverage via integration tests (#10)
- [x] updated README
- [x] minimal docs: add some keywords for libertem live sim etc.
- [x] sample notebook!
- [x] Update override_requirements.txt after LiberTEM 0.7 is released

## Maybe

- [x] support for more bit depths of the Merlin Medipix
- [ ] <strike>cleanly separate libertem-dependent parts, so this project can be used in a non-LiberTEM context, even without installing LiberTEM at all</strike>

@uellue anything I missed?

**Comment by uellue** [comment]
Discussion with @sk1p: The parts under "Maybe" can be done in 0.2. :-)

**Comment by uellue** [comment]
- [ ] When updating the version to the release and tagging it, we can remove the note from the README about not being released yet.
