### ISSUE TITLE
Replace Merlin backend w/ a rust based one

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-live#160]
With the latest QD software on quad systems, when streaming the data over the network, our "naive" Python-based implementation becomes a bottleneck. Take advantage of the infrastructure built for DECTRIS support and use a proper SHM arena for data transfers.

# TODO

- [x] Merge necessary MIB sim fixes from https://github.com/LiberTEM/LiberTEM-live/pull/159
- [ ] Review and merge https://github.com/LiberTEM/LiberTEM-rs/pull/65
- [ ] Release first `libertem_qd_mpx` package on pypi and conda (including updated packages for `libertem_asi_tpx` and `libertem_dectris`)
- [ ] Update LiberTEM-live to take advantage of the new interfaces (onging work in https://github.com/LiberTEM/LiberTEM-live/pull/161)
